#!/usr/bin/env bash
# Start local DEV stack:
#   - Postgres ONLY in Docker
#   - API (backend) local with bun --hot
#   - Frontend local with Vite
#
# Usage:
#   ./scripts/dev-up.sh
#   ./scripts/dev-up.sh --seed          # force prisma seed after DB is up
#   ./scripts/dev-up.sh --restore FILE  # restore dump into docker DB
#   ./scripts/dev-up.sh --no-web        # API + DB only
#   ./scripts/dev-up.sh --down          # stop local API/web (keeps docker db)
#
# Verify:
#   ./scripts/dev-up.sh --check
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

DEV_DIR="$ROOT_DIR/.dev"
API_PID_FILE="$DEV_DIR/api.pid"
WEB_PID_FILE="$DEV_DIR/web.pid"
API_LOG="$DEV_DIR/api.log"
WEB_LOG="$DEV_DIR/web.log"
ENV_RUNTIME="$DEV_DIR/runtime.env"

# ── defaults ────────────────────────────────────────────────────────
API_PORT="${PORT:-3000}"
WEB_PORT="${FRONTEND_PORT:-5173}"
DB_HOST_PORT="${DB_PORT:-5433}"
DB_USER_DEFAULT="oscarcode"
DB_PASS_DEFAULT="postgres_secure_pass"
DB_NAME_DEFAULT="class1_db"
COMPOSE_DB_SERVICE="db"
DO_SEED=0
DO_RESTORE=""
DO_WEB=1
MODE="up"

# ── args ────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed) DO_SEED=1; shift ;;
    --restore)
      DO_RESTORE="${2:-}"
      [[ -n "$DO_RESTORE" ]] || { echo "Usage: --restore path/to.dump"; exit 1; }
      shift 2
      ;;
    --no-web) DO_WEB=0; shift ;;
    --down) MODE="down"; shift ;;
    --check) MODE="check"; shift ;;
    -h|--help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

mkdir -p "$DEV_DIR"

log()  { printf '→ %s\n' "$*"; }
ok()   { printf '✓ %s\n' "$*"; }
err()  { printf '✗ %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1"; }

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

port_in_use() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$port" -sTCP:LISTEN -P -n >/dev/null 2>&1
  else
    nc -z 127.0.0.1 "$port" >/dev/null 2>&1
  fi
}

pid_alive() {
  local pid="${1:-}"
  [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null
}

stop_pidfile() {
  local file="$1"
  local name="$2"
  if [[ -f "$file" ]]; then
    local pid
    pid="$(tr -d '[:space:]' <"$file" || true)"
    if pid_alive "$pid"; then
      log "Stopping $name (pid $pid)..."
      kill "$pid" 2>/dev/null || true
      for _ in $(seq 1 20); do
        pid_alive "$pid" || break
        sleep 0.15
      done
      if pid_alive "$pid"; then
        kill -9 "$pid" 2>/dev/null || true
      fi
      ok "Stopped $name"
    fi
    rm -f "$file"
  fi
}

# Kill listeners on a port that belong to this project (best-effort)
free_port_if_ours() {
  local port="$1"
  local pattern="$2"
  if ! command -v lsof >/dev/null 2>&1; then
    return 0
  fi
  local pids
  pids="$(lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  [[ -z "$pids" ]] && return 0
  local pid
  for pid in $pids; do
    local args
    args="$(ps -p "$pid" -o args= 2>/dev/null || true)"
    if [[ "$args" == *"$pattern"* ]] || [[ "$args" == *"$ROOT_DIR"* ]]; then
      log "Freeing port $port (pid $pid: $args)"
      kill "$pid" 2>/dev/null || true
      sleep 0.3
      kill -9 "$pid" 2>/dev/null || true
    fi
  done
}

load_base_env() {
  if [[ -f "$ROOT_DIR/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$ROOT_DIR/.env"
    set +a
  fi
  DB_USER="${DB_USER:-$DB_USER_DEFAULT}"
  # empty password in .env is useless for docker auth — use secure default
  if [[ -z "${DB_PASSWORD:-}" ]]; then
    DB_PASSWORD="$DB_PASS_DEFAULT"
  fi
  DB_NAME="${DB_NAME:-$DB_NAME_DEFAULT}"
  DB_PORT="${DB_PORT:-$DB_HOST_PORT}"
  # Prefer host port that avoids conflict with other local postgres (5432 often taken)
  if [[ "${DB_PORT}" == "5432" ]] && port_in_use 5432; then
    # if our class1-db already maps 5433, keep using 5433
    if docker ps --format '{{.Names}} {{.Ports}}' 2>/dev/null | grep -q 'class1-db.*5433'; then
      DB_PORT=5433
    else
      DB_PORT=5433
      log "Host 5432 busy — publishing docker Postgres on ${DB_PORT}"
    fi
  fi
  API_PORT="${PORT:-$API_PORT}"
  ACCESS_TOKEN_SECRET="${ACCESS_TOKEN_SECRET:-dev-access-token-secret-change-me}"
  DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:${DB_PORT}/${DB_NAME}?schema=public"
}

write_runtime_env() {
  cat >"$ENV_RUNTIME" <<EOF
# Generated by scripts/dev-up.sh — do not commit
NODE_ENV=development
PORT=${API_PORT}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
DB_PORT=${DB_PORT}
DB_HOST=127.0.0.1
ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
DATABASE_URL=${DATABASE_URL}
API_URL=http://127.0.0.1:${API_PORT}/api/v1
VITE_API_BASE_URL=/api
EOF
}

cmd_down() {
  log "Stopping local API + frontend (Docker DB kept running)..."
  stop_pidfile "$API_PID_FILE" "API"
  stop_pidfile "$WEB_PID_FILE" "frontend"
  free_port_if_ours "$API_PORT" "src/index.ts"
  free_port_if_ours "$WEB_PORT" "vite"
  ok "Local dev processes stopped"
}

stop_docker_app_services() {
  log "Stopping Docker app services (api / frontend / mcp) — DB stays..."
  # Only stop if they exist; ignore errors
  compose stop api frontend mcp >/dev/null 2>&1 || true
  # If containers were started with old names, stop by name too
  for c in class1-api class1-frontend class1-mcp; do
    if docker ps --format '{{.Names}}' | grep -qx "$c"; then
      docker stop "$c" >/dev/null 2>&1 || true
    fi
  done
  ok "Docker api/frontend/mcp stopped (or were already stopped)"
}

start_docker_db() {
  need docker
  log "Starting Postgres in Docker only (service: ${COMPOSE_DB_SERVICE})..."
  export DB_PORT DB_USER DB_PASSWORD DB_NAME
  compose up -d "$COMPOSE_DB_SERVICE"

  log "Waiting for database healthy..."
  local i
  for i in $(seq 1 60); do
    if compose exec -T "$COMPOSE_DB_SERVICE" \
      pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; then
      ok "Database ready on localhost:${DB_PORT}"
      return 0
    fi
    sleep 1
  done
  die "Database did not become ready in time"
}

db_has_tasks() {
  compose exec -T "$COMPOSE_DB_SERVICE" \
    psql -U "$DB_USER" -d "$DB_NAME" -tAc "SELECT count(*) FROM tasks" 2>/dev/null \
    | tr -d '[:space:]' || echo "0"
}

ensure_schema_and_data() {
  need bun
  log "Prisma generate + db push (schema into docker DB)..."
  export DATABASE_URL
  bunx prisma generate >/dev/null
  bunx prisma db push --skip-generate --accept-data-loss=false 2>&1 | tail -5 || {
    # first-time empty DB may need push without strictness
    bunx prisma db push --skip-generate 2>&1 | tail -8
  }

  if [[ -n "$DO_RESTORE" ]]; then
    [[ -f "$DO_RESTORE" ]] || die "Restore file not found: $DO_RESTORE"
    log "Restoring dump into docker DB: $DO_RESTORE"
    # custom format preferred
    if [[ "$DO_RESTORE" == *.sql ]]; then
      compose exec -T "$COMPOSE_DB_SERVICE" \
        psql -U "$DB_USER" -d "$DB_NAME" <"$DO_RESTORE"
    else
      compose exec -T "$COMPOSE_DB_SERVICE" \
        pg_restore -U "$DB_USER" -d "$DB_NAME" \
        --no-owner --no-privileges --clean --if-exists 2>/dev/null <"$DO_RESTORE" \
        || compose exec -T "$COMPOSE_DB_SERVICE" \
             pg_restore -U "$DB_USER" -d "$DB_NAME" \
             --no-owner --no-privileges <"$DO_RESTORE" || true
    fi
    ok "Restore attempted"
  fi

  local count
  count="$(db_has_tasks)"
  if [[ "$DO_SEED" == "1" ]] || [[ "$count" == "0" || -z "$count" ]]; then
    log "Seeding database (tasks empty or --seed)..."
    bun run db:seed
    count="$(db_has_tasks)"
  fi
  ok "DB tasks count: ${count:-?}"
}

# Clone: take a snapshot of current docker DB into backups/ (documentation of "clone")
# and ensure docker is the single DB source for local dev.
clone_snapshot() {
  local stamp out
  stamp="$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$ROOT_DIR/backups"
  out="$ROOT_DIR/backups/${DB_NAME}-dev-${stamp}.dump"
  log "Cloning docker DB snapshot → $out"
  compose exec -T "$COMPOSE_DB_SERVICE" \
    pg_dump -U "$DB_USER" -d "$DB_NAME" \
    --format=custom --no-owner --no-privileges >"$out" || {
      err "Snapshot failed (non-fatal)"
      return 0
    }
  if [[ -s "$out" ]]; then
    ln -sfn "$(basename "$out")" "$ROOT_DIR/backups/${DB_NAME}-latest.dump"
    ok "Clone snapshot: $out ($(du -h "$out" | awk '{print $1}'))"
  fi
}

start_api() {
  need bun
  free_port_if_ours "$API_PORT" "src/index.ts"
  if port_in_use "$API_PORT"; then
    die "Port ${API_PORT} is already in use by another process. Free it or set PORT=...."
  fi

  log "Starting API locally on :${API_PORT} (bun --hot)..."
  set -a
  # shellcheck disable=SC1090
  source "$ENV_RUNTIME"
  set +a

  nohup bun --hot src/index.ts >"$API_LOG" 2>&1 &
  echo $! >"$API_PID_FILE"
  ok "API pid $(cat "$API_PID_FILE") — log: $API_LOG"

  log "Waiting for API health..."
  local i
  for i in $(seq 1 40); do
    if curl -sf "http://127.0.0.1:${API_PORT}/api/v1/health" \
      | grep -q '"status":"healthy"'; then
      ok "API healthy → http://127.0.0.1:${API_PORT}/api/v1/health"
      return 0
    fi
    sleep 0.5
  done
  err "API failed to become healthy. Last log lines:"
  tail -40 "$API_LOG" >&2 || true
  die "API health check failed"
}

start_web() {
  need bun
  free_port_if_ours "$WEB_PORT" "vite"
  if port_in_use "$WEB_PORT"; then
    # try next free-ish port
    local alt=$((WEB_PORT + 1))
    if ! port_in_use "$alt"; then
      WEB_PORT="$alt"
      log "Using frontend port ${WEB_PORT}"
    else
      die "Port ${WEB_PORT} in use. Free it or set FRONTEND_PORT=...."
    fi
  fi

  if [[ ! -d "$ROOT_DIR/frontend/node_modules" ]]; then
    log "Installing frontend deps..."
    bun install --cwd frontend
  fi

  log "Starting frontend locally on :${WEB_PORT} (Vite)..."
  set -a
  # shellcheck disable=SC1090
  source "$ENV_RUNTIME"
  set +a

  # Vite: proxy /api → local backend (vite.config.ts targets :3000)
  (
    cd "$ROOT_DIR/frontend"
    # Prefer bunx vite so port/host flags are reliable
    nohup bunx vite --host 127.0.0.1 --port "$WEB_PORT" >"$WEB_LOG" 2>&1 &
    echo $! >"$WEB_PID_FILE"
  )
  ok "Frontend pid $(cat "$WEB_PID_FILE") — log: $WEB_LOG"

  log "Waiting for Vite..."
  local i
  for i in $(seq 1 40); do
    if curl -sf "http://127.0.0.1:${WEB_PORT}/" >/dev/null 2>&1; then
      ok "Frontend up → http://127.0.0.1:${WEB_PORT}/"
      return 0
    fi
    sleep 0.5
  done
  err "Frontend failed. Last log lines:"
  tail -40 "$WEB_LOG" >&2 || true
  die "Frontend health check failed"
}

cmd_check() {
  load_base_env
  if [[ -f "$ENV_RUNTIME" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_RUNTIME"
    set +a
    API_PORT="${PORT:-$API_PORT}"
  fi

  local failed=0
  echo "=== class1 dev stack check ==="

  if docker ps --format '{{.Names}}' | grep -qx class1-db; then
    ok "Docker DB container class1-db is running"
  else
    err "Docker DB class1-db is NOT running"
    failed=1
  fi

  if docker ps --format '{{.Names}}' | grep -Eq 'class1-api|class1-frontend|class1-mcp'; then
    err "Docker app containers still running (should be local-only for API/web):"
    docker ps --format '  {{.Names}} {{.Status}}' | grep class1 || true
    failed=1
  else
    ok "No Docker API/frontend/mcp (local mode)"
  fi

  if curl -sf "http://127.0.0.1:${API_PORT}/api/v1/health" | grep -q healthy; then
    ok "API health OK on :${API_PORT}"
  else
    err "API not healthy on :${API_PORT}"
    failed=1
  fi

  # Auth + tasks smoke
  local login tasks_code
  login="$(curl -sf -X POST "http://127.0.0.1:${API_PORT}/api/v1/auth/login" \
    -H 'Content-Type: application/json' \
    -d '{"email":"alice@example.com","password":"Password123!"}' || true)"
  if printf '%s' "$login" | grep -q accessToken; then
    ok "Login OK (alice@example.com)"
    local token
    token="$(printf '%s' "$login" | python3 -c 'import sys,json; print(json.load(sys.stdin)["data"]["accessToken"])' 2>/dev/null || true)"
    if [[ -n "$token" ]]; then
      tasks_code="$(curl -s -o /tmp/class1-tasks-check.json -w '%{http_code}' \
        "http://127.0.0.1:${API_PORT}/api/v1/tasks?limit=100" \
        -H "Authorization: Bearer $token")"
      if [[ "$tasks_code" == "200" ]]; then
        local n
        n="$(python3 -c 'import json; print(len(json.load(open("/tmp/class1-tasks-check.json")).get("data") or []))' 2>/dev/null || echo '?')"
        ok "GET /tasks → HTTP 200 ($n items)"
      else
        err "GET /tasks → HTTP $tasks_code"
        failed=1
      fi
    fi
  else
    err "Login failed (seed users missing? re-run with --seed)"
    failed=1
  fi

  local web_ok=0
  for p in "$WEB_PORT" 5173 5174 8080; do
    if curl -sf "http://127.0.0.1:${p}/" >/dev/null 2>&1; then
      ok "Frontend responds on :${p}"
      web_ok=1
      break
    fi
  done
  if [[ "$web_ok" != "1" ]]; then
    err "Frontend not responding on common ports"
    failed=1
  fi

  echo "=============================="
  if [[ "$failed" == "0" ]]; then
    ok "All checks passed"
    exit 0
  fi
  die "Some checks failed"
}

cmd_up() {
  need docker
  need bun
  need curl

  load_base_env
  write_runtime_env

  log "Project: $ROOT_DIR"
  log "Mode: DB=Docker | API=local bun | Frontend=local Vite"

  stop_docker_app_services
  # Stop previous local dev pids
  stop_pidfile "$API_PID_FILE" "API"
  stop_pidfile "$WEB_PID_FILE" "frontend"

  start_docker_db
  ensure_schema_and_data
  clone_snapshot

  if [[ ! -d "$ROOT_DIR/node_modules" ]]; then
    log "Installing root deps..."
    bun install
  fi

  start_api
  if [[ "$DO_WEB" == "1" ]]; then
    start_web
  fi

  echo
  ok "Dev stack is up"
  echo
  echo "  API       http://127.0.0.1:${API_PORT}/api/v1/health"
  echo "  Frontend  http://127.0.0.1:${WEB_PORT}/"
  echo "  DB        localhost:${DB_PORT}  user=${DB_USER}  db=${DB_NAME}  (docker: class1-db)"
  echo "  Runtime   $ENV_RUNTIME"
  echo "  Logs      $API_LOG"
  [[ "$DO_WEB" == "1" ]] && echo "            $WEB_LOG"
  echo
  echo "  CLI       task get all"
  echo "  Check     ./scripts/dev-up.sh --check"
  echo "  Stop      ./scripts/dev-up.sh --down"
  echo

  # Final verification
  cmd_check
}

case "$MODE" in
  down)  load_base_env; cmd_down ;;
  check) cmd_check ;;
  up)    cmd_up ;;
esac
